name: Build and Test - API Service

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

env:
  NODE_VERSION: '18'
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [amd64, arm64]
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ env.NODE_VERSION }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ env.NODE_VERSION }}-

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: |
          if grep -q '"lint"' package.json; then
            npm run lint
          else
            echo "No linting script found, skipping..."
          fi

      - name: Run unit tests
        run: npm run test:coverage
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/testdb

      - name: Run integration tests
        run: |
          if grep -q '"test:integration"' package.json; then
            npm run test:integration
          else
            echo "No integration tests found, skipping..."
          fi
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/testdb

      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results-api-service-${{ matrix.architecture }}
          path: |
            coverage/
            test-results.xml
          retention-days: 30

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: coverage/lcov.info
          flags: api-service
          name: api-service-coverage
          fail_ci_if_error: false

      - name: Set up QEMU for multi-arch builds
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-api-service-${{ matrix.architecture }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-api-service-${{ matrix.architecture }}-
            ${{ runner.os }}-buildx-api-service-

      - name: Build Docker image (test)
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/${{ matrix.architecture }}
          push: false
          tags: api-service:test-${{ matrix.architecture }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          target: test

      - name: Run container tests
        run: |
          # Test that the container starts correctly
          docker run --rm -d --name api-service-test -p 3001:3001 \
            -e DATABASE_URL=postgresql://postgres:postgres@host.docker.internal:5432/testdb \
            api-service:test-${{ matrix.architecture }}
          
          # Wait for container to be ready
          timeout 30 bash -c 'until curl -f http://localhost:3001/health; do sleep 1; done'
          
          # Run basic smoke tests
          curl -f http://localhost:3001/api/status || exit 1
          
          # Cleanup
          docker stop api-service-test

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  security-scan:
    runs-on: ubuntu-latest
    needs: build-and-test
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image for scanning
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: api-service:scan
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'api-service:scan'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

  performance-tests:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Install performance testing tools
        run: npm install -g artillery

      - name: Start API service
        run: |
          npm start &
          API_PID=$!
          echo "API_PID=$API_PID" >> $GITHUB_ENV
          
          # Wait for API to be ready
          timeout 30 bash -c 'until curl -f http://localhost:3001/health; do sleep 1; done'
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/testdb

      - name: Run performance tests
        run: |
          if [ -f "performance-tests.yml" ]; then
            artillery run performance-tests.yml --output performance-report.json
            artillery report performance-report.json --output performance-report.html
          else
            echo "No performance tests found, running basic load test..."
            artillery quick --count 100 --num 10 http://localhost:3001/api/status
          fi

      - name: Upload performance results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: performance-results
          path: |
            performance-report.json
            performance-report.html
          retention-days: 30

      - name: Cleanup
        if: always()
        run: |
          if [ ! -z "$API_PID" ]; then
            kill $API_PID || true
          fi

  build-summary:
    needs: [build-and-test, security-scan, performance-tests]
    if: always()
    runs-on: ubuntu-latest
    
    steps:
      - name: Build Summary
        run: |
          echo "## Build Summary - API Service" >> $GITHUB_STEP_SUMMARY
          echo "| Component | Status | Architectures |" >> $GITHUB_STEP_SUMMARY
          echo "|-----------|--------|---------------|" >> $GITHUB_STEP_SUMMARY
          echo "| Build & Test | ${{ needs.build-and-test.result }} | amd64, arm64 |" >> $GITHUB_STEP_SUMMARY
          echo "| Security Scan | ${{ needs.security-scan.result }} | amd64 |" >> $GITHUB_STEP_SUMMARY
          echo "| Performance Tests | ${{ needs.performance-tests.result }} | amd64 |" >> $GITHUB_STEP_SUMMARY