# Security Configuration for DevOps Pipeline

# Vulnerability Scanning Configuration
vulnerability_scanning:
  # Trivy configuration
  trivy:
    severity_levels: ["CRITICAL", "HIGH", "MEDIUM"]
    ignore_unfixed: false
    timeout: "10m"
    cache_dir: "/tmp/trivy-cache"
    
  # Grype configuration  
  grype:
    severity_cutoff: "medium"
    fail_on_severity: "high"
    scope: "all-layers"
    
  # Snyk configuration
  snyk:
    severity_threshold: "medium"
    monitor: true
    fail_on: "upgradable"

# Static Application Security Testing (SAST)
sast:
  # CodeQL configuration
  codeql:
    languages: ["javascript", "typescript"]
    queries: ["security-extended", "security-and-quality"]
    
  # Semgrep configuration
  semgrep:
    rulesets:
      - "p/security-audit"
      - "p/secrets"
      - "p/owasp-top-ten"
      - "p/javascript"
      - "p/nodejs"
      - "p/docker"

# Secret Scanning Configuration
secret_scanning:
  # TruffleHog configuration
  trufflehog:
    only_verified: true
    include_paths: ["src/", "config/", "scripts/"]
    exclude_paths: ["node_modules/", ".git/", "test/"]
    
  # GitLeaks configuration
  gitleaks:
    config_path: ".gitleaks.toml"
    verbose: true
    redact: true

# Container Security
container_security:
  # Base image requirements
  base_images:
    allowed_registries:
      - "docker.io"
      - "gcr.io"
      - "ghcr.io"
      - "quay.io"
    
    preferred_images:
      - "node:18-alpine"
      - "nginx:alpine"
      - "postgres:15-alpine"
    
  # Security requirements
  requirements:
    run_as_non_root: true
    read_only_root_filesystem: true
    no_privileged_containers: true
    drop_all_capabilities: true
    
  # Resource limits
  resource_limits:
    memory_limit_required: true
    cpu_limit_required: true
    max_memory: "1Gi"
    max_cpu: "1000m"

# Kubernetes Security Policies
kubernetes_security:
  # Pod Security Standards
  pod_security:
    enforce_level: "restricted"
    audit_level: "restricted"
    warn_level: "restricted"
    
  # Network Policies
  network_policies:
    default_deny_all: true
    require_explicit_allow: true
    
  # RBAC Requirements
  rbac:
    principle_of_least_privilege: true
    no_cluster_admin: true
    service_account_required: true

# Compliance Requirements
compliance:
  # Security frameworks
  frameworks:
    - "CIS Kubernetes Benchmark"
    - "NIST Cybersecurity Framework"
    - "OWASP Top 10"
    - "PCI DSS" # if applicable
    
  # Audit requirements
  audit:
    log_all_api_calls: true
    retain_logs_days: 90
    monitor_privileged_operations: true

# Incident Response
incident_response:
  # Severity levels
  severity_levels:
    critical:
      response_time: "15 minutes"
      escalation_time: "30 minutes"
    high:
      response_time: "1 hour"
      escalation_time: "4 hours"
    medium:
      response_time: "4 hours"
      escalation_time: "24 hours"
    low:
      response_time: "24 hours"
      escalation_time: "72 hours"
      
  # Notification channels
  notifications:
    slack_webhook: "${SLACK_SECURITY_WEBHOOK}"
    email_list: ["security@company.com"]
    pagerduty_key: "${PAGERDUTY_INTEGRATION_KEY}"

# Security Metrics and Monitoring
monitoring:
  # Key metrics to track
  metrics:
    - "vulnerability_count_by_severity"
    - "time_to_patch_critical_vulnerabilities"
    - "security_scan_coverage"
    - "failed_security_scans"
    - "secret_detection_rate"
    
  # Dashboards
  dashboards:
    grafana_dashboard_id: "security-overview"
    prometheus_alerts: true
    
# Automation Rules
automation:
  # Auto-remediation
  auto_remediation:
    patch_low_severity: true
    update_base_images: true
    rotate_secrets: false # manual approval required
    
  # Blocking rules
  blocking_rules:
    block_critical_vulnerabilities: true
    block_secret_commits: true
    block_policy_violations: true
    
# Training and Awareness
security_training:
  # Required training
  required_courses:
    - "Secure Coding Practices"
    - "Container Security"
    - "Kubernetes Security"
    - "DevSecOps Fundamentals"
    
  # Certification requirements
  certifications:
    security_team: ["CISSP", "CISM", "CEH"]
    developers: ["CSSLP", "GWEB"]