---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-app
  namespace: default
  labels:
    app: web-app
    component: frontend
  annotations:
    kubernetes.io/description: "Service account for web-app deployment"
automountServiceAccountToken: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-service
  namespace: default
  labels:
    app: api-service
    component: backend
  annotations:
    kubernetes.io/description: "Service account for api-service deployment"
automountServiceAccountToken: false